# Generated by Django 4.2.10 on 2024-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='кадастровый номер')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('date_query', models.DateField(auto_now=True, verbose_name='дата запроса')),
                ('server_response', models.BooleanField(blank=True, null=True, verbose_name='ответ сервера')),
            ],
        ),
    ]
