# Generated by Django 4.2.10 on 2024-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': 'запрос'},
        ),
        migrations.AlterField(
            model_name='query',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='кадастровый номер'),
        ),
    ]
