# Generated by Django 4.2.10 on 2024-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_query_options_alter_query_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='number',
            field=models.CharField(max_length=50, verbose_name='кадастровый номер'),
        ),
    ]
